name: upsessions
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  go_router: ^17.0.0
  get_it: ^9.1.0
  equatable: ^2.0.7
  url_launcher: ^6.3.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.0
  cloud_functions: ^6.0.4
  firebase_messaging: ^16.0.0
  image_picker: ^1.1.2
  app_links: ^6.4.0
  freezed: ^3.2.3
  json_annotation: ^4.9.0
  locator: ^0.0.0-dev.2
  firebase_app_check: ^0.4.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  json_serializable: ^6.11.2
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
